export function renderDashboard(): Response {
  const authAction =
    '<form action="/auth/logout" method="post"><button class="secondary" type="submit">Logga ut</button></form>';
  return new Response(DASHBOARD_HTML.replace("<!--AUTH_ACTION-->", authAction), {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "content-security-policy":
        "default-src 'self'; script-src 'self' https://challenges.cloudflare.com; style-src 'self'; connect-src 'self' https://challenges.cloudflare.com; frame-src https://challenges.cloudflare.com; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",
      "x-content-type-options": "nosniff",
      "referrer-policy": "no-referrer",
    },
  });
}

export function renderDashboardStyles(): Response {
  return new Response(DASHBOARD_CSS, {
    headers: {
      "content-type": "text/css; charset=utf-8",
      "cache-control": "no-store",
      "x-content-type-options": "nosniff",
    },
  });
}

export function renderDashboardScript(): Response {
  return new Response(DASHBOARD_JS, {
    headers: {
      "content-type": "text/javascript; charset=utf-8",
      "cache-control": "no-store",
      "x-content-type-options": "nosniff",
    },
  });
}

const DASHBOARD_HTML = `<!doctype html>
<html lang="sv">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Jobbautomation</title>
<link rel="stylesheet" href="/assets/dashboard.css">
</head>
<body>
<header class="page-head"><div><p class="eyebrow">Avkroken / Jobb</p><h1>Jobbautomation</h1><p class="muted">StudentConsulting → Arbetsförmedlingen · exakt 10 verifierade ansökningar per månad</p><p id="freshness" class="muted"></p></div><!--AUTH_ACTION--></header>
<nav class="tabs" aria-label="Dashboard">
<a href="#overview" data-tab="overview">Översikt</a>
<a href="#applications" data-tab="applications">Ansökningar</a>
<a href="#runs" data-tab="runs">Körningar</a>
<a href="#report" data-tab="report">Aktivitetsrapport</a>
<a href="#system" data-tab="system">System</a>
</nav>
<main>
<section data-panel="overview"><div class="card">Laddar…</div></section>
<section data-panel="applications" hidden></section>
<section data-panel="runs" hidden></section>
<section data-panel="report" hidden></section>
<section data-panel="system" hidden></section>
</main>
<dialog id="runDialog"><div class="dialog-head"><h2 id="runTitle">Körningsdetaljer</h2><button id="closeRun" class="secondary">Stäng</button></div><div id="runBody"></div></dialog>
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" async defer></script>
<script src="/assets/dashboard.js" defer></script>
</body>
</html>`;

const DASHBOARD_CSS = `:root{font-family:Inter,system-ui,sans-serif;color-scheme:dark;background:#0b0d10;color:#f2f4f7;--panel:#15191f;--line:#272d36;--muted:#9ca3af;--ok:#78dba9;--warn:#ffd166;--bad:#ff7b7b}*{box-sizing:border-box}body{margin:0 auto;padding:24px;max-width:1280px}h1{margin:0;font-size:clamp(30px,5vw,44px)}h2{font-size:18px;margin:0 0 12px}.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.page-head form{margin:0}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:var(--muted);margin:0 0 6px}.muted{color:var(--muted)}.tabs{display:flex;gap:8px;overflow:auto;margin:24px 0}.tabs a{color:#ddd;text-decoration:none;border:1px solid var(--line);border-radius:999px;padding:9px 12px;white-space:nowrap}.tabs a[aria-current=page]{background:#f2f4f7;color:#111}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin:14px 0}.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:17px}.big{font-size:34px;font-weight:750}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}.status{font-weight:750}.toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.button,button{border:0;border-radius:9px;padding:10px 14px;font-weight:700;cursor:pointer;background:#f2f4f7;color:#111;text-decoration:none}.secondary{background:#222831!important;color:#f2f4f7!important;border:1px solid var(--line)!important}button:disabled{opacity:.5;cursor:not-allowed}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid var(--line);vertical-align:top}.error{white-space:pre-wrap;color:#ff9a9a}.slots{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.slot{background:#10141a;border:1px solid var(--line);border-radius:10px;padding:10px}.slot.uncertain{border-color:#a96832}.slot.verified{border-color:#39745b}.slot strong{display:block;font-size:20px}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px}.filters input,.filters select{background:#10141a;color:#fff;border:1px solid var(--line);border-radius:8px;padding:9px}.notice{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid var(--line);padding:9px 0}.mono,code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;overflow-wrap:anywhere}dialog{width:min(980px,calc(100vw - 28px));max-height:90vh;overflow:auto;background:var(--panel);color:#fff;border:1px solid var(--line);border-radius:14px;padding:18px}dialog::backdrop{background:#000b}.dialog-head{display:flex;justify-content:space-between;align-items:center}.empty{padding:18px;color:var(--muted)}progress{width:100%}@media(max-width:700px){body{padding:14px}.slots{grid-template-columns:repeat(2,1fr)}}`;

const DASHBOARD_JS = `var dashboard=null,turnstileId=null,turnstileToken='',checkingBankId=false;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function badge(s){var cls=['verified','completed','submitted','captured','saved','sent','free'].includes(s)?'ok':['failed','errored'].includes(s)?'bad':'warn';return '<span class="status '+cls+'">'+esc(s)+'</span>';}
function when(v){if(!v)return '';var d=new Date(v);return Number.isNaN(d.valueOf())?esc(v):esc(new Intl.DateTimeFormat('sv-SE',{dateStyle:'medium',timeStyle:'short'}).format(d));}
async function api(path,options){var r=await fetch(path,options);if(!r.ok)throw new Error(await r.text());return r.json();}
function tab(name){if(!['overview','applications','runs','report','system'].includes(name))name='overview';document.querySelectorAll('[data-panel]').forEach(function(p){p.hidden=p.dataset.panel!==name;});document.querySelectorAll('[data-tab]').forEach(function(a){a.setAttribute('aria-current',a.dataset.tab===name?'page':'false');});}
function renderOverview(d){var attention=d.attention.uncertainSlots+d.attention.failedRuns+d.attention.failedNotifications+d.attention.ambiguousReportItems+(d.attention.activeRun?1:0);var slots=d.quotaSlots.map(function(s){return '<div class="slot '+esc(s.state)+'"><strong>'+esc(s.slot_no)+'</strong>'+badge(s.state)+'<div class="mono">'+esc(s.application_id||'ledig')+'</div></div>';}).join('');var html='<div class="grid"><div class="card"><p class="eyebrow">'+esc(d.applicationMonth)+'</p><h2>Månadsmål</h2><div class="big">'+esc(d.verified)+'/'+esc(d.target)+'</div><progress max="'+d.target+'" value="'+d.verified+'"></progress><p class="muted">'+esc(d.quotaUsed)+'/'+esc(d.target)+' slots upptagna</p></div><div class="card"><p class="eyebrow">Rapport '+esc(d.reportMonth)+'</p><h2>Aktivitetsrapport</h2>'+(d.report?badge(d.report.status):'<span class="muted">Inte skapad än</span>')+'<p>'+esc(d.reportSaved)+'/'+esc(d.target)+' aktiviteter sparade</p><p class="error">'+esc(d.report&&d.report.last_error||'')+'</p></div><div class="card"><p class="eyebrow">Operativt</p><h2>Behöver uppmärksamhet</h2><div class="big '+(attention?'warn':'ok')+'">'+esc(attention)+'</div><p class="muted">Aktiva blockers och osäkra tillstånd</p></div></div><div class="grid"><div class="card"><h2>Quota-slots</h2><div class="slots">'+slots+'</div></div><div class="card"><h2>Aktiva signaler</h2>'+signalRows(d)+'</div></div><div class="grid"><div class="card"><h2>Manuell körning</h2><p>Fail-closed pipeline, tillåten den 1:a–14:e.</p><div id="turnstile"></div><div class="toolbar"><button id="manual" disabled>Kör nu</button><span id="manualResult" class="muted"></span></div></div><div class="card"><h2>Automatiskt säkerhetsläge</h2><div class="status ok">Aktivt</div><p>'+esc(d.automaticMode.schedule)+'</p></div></div>';document.querySelector('[data-panel=overview]').innerHTML=html;setupManual(d.applicationWindowOpen);}
function signalRows(d){var rows=[];if(d.attention.activeRun)rows.push(['Aktiv körning',badge(d.attention.activeRun.status)]);if(d.attention.uncertainSlots)rows.push(['Osäkra quota-slots','<strong class="warn">'+d.attention.uncertainSlots+'</strong>']);if(d.attention.failedRuns)rows.push(['Misslyckade körningar denna månad','<strong class="bad">'+d.attention.failedRuns+'</strong>']);if(d.attention.failedNotifications)rows.push(['Notifieringsfel 30 dagar','<strong class="bad">'+d.attention.failedNotifications+'</strong>']);if(d.attention.ambiguousReportItems)rows.push(['Rapportposter i save_attempted','<strong class="warn">'+d.attention.ambiguousReportItems+'</strong>']);return rows.length?rows.map(function(r){return '<div class="notice"><span>'+r[0]+'</span>'+r[1]+'</div>';}).join(''):'<div class="empty">Inga kända blockers.</div>';}
function renderApplications(d){var html='<div class="card"><h2>Ansökningar</h2><div class="filters"><input id="appSearch" type="search" placeholder="Sök jobb, arbetsgivare, Jobb-ID"><select id="appStatus"><option value="">Alla statusar</option><option>verified</option><option>submitted</option><option>applying</option><option>queued</option><option>needs_user_action</option><option>failed</option></select></div><div class="table-wrap"><table><thead><tr><th>Status</th><th>Jobb</th><th>Ort</th><th>Datum</th><th>Run</th><th>Evidens</th><th>Fel</th></tr></thead><tbody id="appRows"></tbody></table></div></div>';document.querySelector('[data-panel=applications]').innerHTML=html;function rows(){var q=document.getElementById('appSearch').value.toLowerCase(),s=document.getElementById('appStatus').value;var items=d.applications.filter(function(a){return(!s||a.status===s)&&(!q||[a.title,a.employer,a.external_id,a.location].join(' ').toLowerCase().includes(q));});document.getElementById('appRows').innerHTML=items.length?items.map(appRow).join(''):'<tr><td colspan="7" class="empty">Inga träffar.</td></tr>';}document.getElementById('appSearch').oninput=rows;document.getElementById('appStatus').onchange=rows;rows();}
function appRow(a){return '<tr><td>'+badge(a.status)+'</td><td><a href="'+esc(a.source_url)+'" target="_blank" rel="noopener noreferrer">'+esc(a.title)+'</a><br><span class="muted">'+esc(a.employer||'')+'</span><br><code>'+esc(a.external_id)+'</code></td><td>'+esc(a.location||a.country_code||'')+'</td><td>'+when(a.verified_at||a.applied_at||a.created_at)+'</td><td><code>'+esc(a.automation_run_id||'')+'</code></td><td>'+esc(a.evidence_count||0)+'</td><td class="error">'+esc(a.error_code||'')+' '+esc(a.error_message||'')+'</td></tr>';}
function renderRuns(d){var rows=d.runs.map(function(r){return '<tr><td>'+when(r.started_at)+'</td><td>'+esc(r.mode)+'</td><td>'+badge(r.status)+'</td><td>'+esc(r.application_month)+'</td><td>'+esc(r.verified_count)+'/'+esc(r.target_count)+'</td><td>'+(r.probe_status?badge(r.probe_status):'')+'</td><td class="error">'+esc(r.last_error||r.probe_error||'')+'</td><td><button class="secondary runDetail" data-id="'+esc(r.id)+'">Detaljer</button></td></tr>';}).join('');document.querySelector('[data-panel=runs]').innerHTML='<div class="card"><h2>Senaste körningar</h2><div class="table-wrap"><table><thead><tr><th>Start</th><th>Läge</th><th>Status</th><th>Månad</th><th>Verifierade</th><th>Probe</th><th>Fel</th><th></th></tr></thead><tbody>'+rows+'</tbody></table></div></div>';document.querySelectorAll('.runDetail').forEach(function(b){b.onclick=function(){openRun(b.dataset.id);};});}
function renderReport(d){var rows=d.reportActivities.length?d.reportActivities.map(function(i){return '<tr><td>'+badge(i.state)+'</td><td>'+esc(i.title)+'<br><code>'+esc(i.external_id)+'</code></td><td>'+esc(i.employer||'')+'</td><td>'+esc(i.location||i.country_code||'')+'</td><td>'+when(i.applied_at)+'</td><td class="error">'+esc(i.last_error||'')+'</td></tr>';}).join(''):'<tr><td colspan="6" class="empty">Inga rapportposter ännu.</td></tr>';document.querySelector('[data-panel=report]').innerHTML='<div class="grid"><div class="card"><h2>Rapport '+esc(d.reportMonth)+'</h2>'+(d.report?badge(d.report.status):'<span class="muted">Inte skapad än</span>')+'<p>'+esc(d.reportSaved)+'/'+esc(d.target)+' sparade</p><p class="error">'+esc(d.report&&d.report.last_error||'')+'</p></div><div class="card"><h2>Fail-closed</h2><p class="muted"><code>save_attempted</code> återkörs inte blint. Obligatoriska handlingsplanfrågor lämnas till användaren.</p></div></div><div class="card"><h2>Aktiviteter</h2><div class="table-wrap"><table><thead><tr><th>Status</th><th>Jobb</th><th>Arbetsgivare</th><th>Ort</th><th>Ansökt</th><th>Fel</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>';}
function renderSystem(d){var c=d.configuration;var checks=[['StudentConsulting-konto',c.studentConsultingCredentials],['Autosubmit',c.studentConsultingAutoSubmit],['Lämplighetsregler',c.suitabilityPolicy],['BankID-notifiering',c.bankIdNotification]].map(function(x){return '<div class="notice"><span>'+x[0]+'</span><strong class="'+(x[1]?'ok':'bad')+'">'+(x[1]?'OK':'Saknas')+'</strong></div>';}).join('');var n=d.notifications.length?d.notifications.map(function(x){return '<tr><td>'+when(x.created_at)+'</td><td>'+esc(x.kind)+'</td><td>'+esc(x.channel)+'</td><td>'+badge(x.status)+'</td><td><code>'+esc(x.automation_run_id)+'</code></td><td class="error">'+esc(x.error_message||'')+'</td></tr>';}).join(''):'<tr><td colspan="6" class="empty">Inga notifieringar sparade.</td></tr>';document.querySelector('[data-panel=system]').innerHTML='<div class="grid"><div class="card"><h2>Runtime-konfiguration</h2>'+checks+'</div><div class="card"><h2>Automation</h2><p>'+esc(d.automaticMode.applicationWindow)+'</p><p>'+esc(d.automaticMode.schedule)+'</p></div></div><div class="card"><h2>Notifieringshistorik</h2><div class="table-wrap"><table><thead><tr><th>Tid</th><th>Typ</th><th>Kanal</th><th>Status</th><th>Körning</th><th>Fel</th></tr></thead><tbody>'+n+'</tbody></table></div></div>';}
async function openRun(id){var dlg=document.getElementById('runDialog'),body=document.getElementById('runBody');body.innerHTML='<div class="empty">Laddar…</div>';dlg.showModal();try{var d=await api('/api/runs/'+encodeURIComponent(id));document.getElementById('runTitle').textContent=id;var apps=d.applications.map(function(a){return '<div class="notice"><span>'+esc(a.title)+' <code>'+esc(a.external_id)+'</code></span>'+badge(a.status)+'</div>';}).join('')||'<div class="empty">Inga ansökningar.</div>';var attempts=d.attempts.map(function(a){return '<tr><td>'+esc(a.attempt_no)+'</td><td><code>'+esc(a.application_id)+'</code></td><td>'+badge(a.status)+'</td><td>'+when(a.started_at)+'</td><td class="error">'+esc(a.error_code||'')+' '+esc(a.error_message||'')+'</td></tr>';}).join('');var evidence=d.evidence.map(function(e){return '<div class="notice"><span><strong>'+esc(e.kind)+'</strong><br><code>'+esc(e.object_key)+'</code><br><span class="muted">sha256: '+esc(e.sha256||'inte lagrad')+'</span></span><span>'+when(e.created_at)+'</span></div>';}).join('')||'<div class="empty">Ingen evidensmetadata.</div>';body.innerHTML='<div class="card"><h2>Run</h2>'+badge(d.run.status)+'<p class="mono">'+esc(d.run.workflow_instance_id||'')+'</p><p class="error">'+esc(d.run.last_error||'')+'</p></div><div class="card"><h2>Ansökningar</h2>'+apps+'</div><div class="card"><h2>Försök</h2><div class="table-wrap"><table><tbody>'+attempts+'</tbody></table></div></div><div class="card"><h2>Evidensmetadata</h2>'+evidence+'</div>';}catch(e){body.innerHTML='<div class="card bad">'+esc(e.message)+'</div>';}}
function setupManual(open){var b=document.getElementById('manual');if(!b)return;function sync(){b.disabled=!open||!turnstileToken;}if(window.turnstile&&turnstileId===null){turnstileId=window.turnstile.render('#turnstile',{sitekey:'0x4AAAAAADtfk0hF05HrDLLJ',action:'manual_run',callback:function(t){turnstileToken=t;sync();},'expired-callback':function(){turnstileToken='';sync();}});}b.onclick=async function(){if(!turnstileToken)return;var out=document.getElementById('manualResult');b.disabled=true;out.textContent=' Startar…';try{var r=await api('/api/runs/manual',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({turnstileToken:turnstileToken})});out.textContent=' Startad: '+r.runId;}catch(e){out.textContent=' '+e.message;}finally{turnstileToken='';if(window.turnstile&&turnstileId!==null)window.turnstile.reset(turnstileId);setTimeout(load,250);}};sync();}
async function bankId(){if(checkingBankId||!dashboard)return;var r=dashboard.runs.find(function(x){return x.status==='needs_user_auth'&&x.auth_live_view_url;});if(!r)return;checkingBankId=true;try{var x=await api('/api/runs/'+encodeURIComponent(r.id)+'/bankid/check',{method:'POST'});if(x.authenticated)load();}catch(_){}finally{checkingBankId=false;}}
async function load(){try{var d=await api('/api/dashboard');dashboard=d;document.getElementById('freshness').textContent='Uppdaterad '+when(d.generatedAt);renderOverview(d);renderApplications(d);renderRuns(d);renderReport(d);renderSystem(d);tab((location.hash||'#overview').slice(1));setTimeout(bankId,1000);}catch(e){document.querySelector('[data-panel=overview]').innerHTML='<div class="card bad">'+esc(e.message)+'</div>';}}
document.querySelectorAll('[data-tab]').forEach(function(a){a.onclick=function(e){e.preventDefault();location.hash=a.dataset.tab;tab(a.dataset.tab);};});window.onhashchange=function(){tab((location.hash||'#overview').slice(1));};document.getElementById('closeRun').onclick=function(){document.getElementById('runDialog').close();};load();setInterval(load,10000);`;
