documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

portal:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/portal/**"

skvallerbyttan:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/skvallerbyttan/**"

jobb:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/jobb/**"

dumpen:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/dumpen/**"

spam-filter:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/spam-filter/**"
