#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

_clear
printf '\n%s%s  Portal · credential/provider prerequisite wizard%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  Inga token- eller secretvärden samlas in, skrivs eller visas.%s\n\n' "$DIM" "$RESET"
pause "Ready to verify Portal provider state?"

stage "Cloudflare Access · logo-admin"
say "Verifiera den path-specifika Access-gränsen framför Portalens logotypadministration."
open_url "https://dash.cloudflare.com/"
step "Öppna Zero Trust → Access → Applications och lokalisera applikationen som skyddar /admin/logos och /api/admin/logos."
step "Verifiera team domain https://avkroken.cloudflareaccess.com och att appens AUD exakt matchar ACCESS_LOGO_ADMIN_AUD i wrangler.jsonc."
step "Verifiera att policyn fortfarande kräver avsedd identitet och inte har en bred bypass/service-token som gör adminytan publik."
open_url "https://avkroken.denied.se/admin/logos"
step "Använd en färsk privat webbläsarsession och slutför Access-inloggningen. Adminsidan ska öppnas utan 401, 403 eller 503."
if ! confirm "Är Access-app, policy, AUD och färsk admininloggning verifierade?"; then
  warn "Behandla Portal-admin som overifierad tills både providerpolicy och origin-JWT fungerar."
  exit 2
fi

stage "R2 · PORTAL_LOGOS"
say "Verifiera den dedikerade production-bucketen och Portalens avsedda syntetiska canary."
open_url "https://dash.cloudflare.com/"
step "Öppna R2 och verifiera bucket avkroken-portal-logos. Production-Workern ska binda den som PORTAL_LOGOS; preview ska sakna production-R2-binding."
open_url "https://avkroken.denied.se/admin/logos"
step "Kör admin-UI:ts 'Kör verifiering'. Canaryn ska skapa en syntetisk SVG, verifiera listning/metadata/public URL, ersätta, ladda ned, radera och avsluta med verifierad 404."
step "Om canaryn avbryts: kontrollera att dess cleanup lyckades innan du försöker igen. Använd inte ett verkligt logoasset som testobjekt."
if ! confirm "Passerar den inbyggda R2-canaryn hela create/read/replace/delete-kedjan?"; then
  warn "R2/admin-write är inte verifierad; fortsätt inte med falskt grön provider-state."
  exit 2
fi

stage "Service Binding · Skvallerbyttan"
say "Verifiera Portalens credential-fria read-only observationsbinding."
open_url "https://dash.cloudflare.com/"
step "Öppna Workers & Pages → avkroken → Settings och verifiera service binding SKVALLERBYTTAN_OBSERVATIONS → skvallerbyttan / PortalObservationsService."
open_url "https://avkroken.denied.se/drift"
step "Verifiera att Drift & insyn laddar aktuell Skvallerbyttan-state via bindingen. Degraded/fallback-data räknas inte som verifierad binding."
step "Ingen bearer-token eller ny Portal-GitHub/Cloudflare-secret ska införas för denna integration."
if ! confirm "Är Service Binding och aktuell read-only driftstate verifierade?"; then
  warn "Fixa binding/entrypoint eller upstream Skvallerbyttan; skapa inte en parallell providercredential i Portal."
  exit 2
fi

stage "Cloudflare Workers Builds · deployidentitet"
say "Verifiera att Portal deployas med Cloudflare Workers Builds och att buildidentiteten fungerar."
open_url "https://dash.cloudflare.com/"
step "Öppna Workers & Pages → avkroken → Builds/Settings."
step "Verifiera repository Avkroken/Avkroken, branch main, root directory apps/portal och production command npm run deploy:workers-builds."
step "Kräv en aktuell lyckad main production-build efter senaste relevanta Access/R2/bindingändring; builden ska köra Portalens verifiering och productiondeploy utan GitHub-hostad Cloudflare-token."
if ! confirm "Finns en aktuell lyckad main-build som bevisar deployidentiteten?"; then
  warn "Deployidentiteten är overifierad tills ordinarie main-build lyckas."
  exit 2
fi

finish

