#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

_clear
printf '\n%s%s  Skvallerbyttan · credential prerequisite wizard%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  Inga token- eller secretvärden samlas in, skrivs eller visas.%s\n\n' "$DIM" "$RESET"
pause "Ready to verify the existing read-only provider state?"

stage "GitHub App · Gamnacken"
say "Verifiera den befintliga GitHub App-installationen och dess read-only permissions."
open_url "https://github.com/settings/apps"
step "Öppna Gamnacken och kontrollera installationens owner/repository-scope."
step "Behåll endast read-behörigheter för de observationsytor som används."
step "Lägg inte till write-permissions. Organization-only ytor får vara not_supported när current owner är en GitHub User."
if ! confirm "Är Gamnacken installerad och fortsatt read-only?"; then
  warn "Åtgärda GitHub App-installation/permissions innan du fortsätter."
  exit 2
fi

stage "Cloudflare API Tokens · R1/R2/R3"
say "Verifiera de tre befintliga tokenklasserna. Skapa inte nya tokens i detta flöde."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "R1: verifiera read-scope för Zone, Workers metadata, D1, KV och R2 inventory enligt docs/permissions.md."
step "R2: verifiera read-scope för Account Settings, Notifications, Audit/Operations och Account Analytics."
step "R3: verifiera read-scope för Access Apps/Policies, cloudflared/Tunnels och övrig Zero Trust/security-observation."
step "Om en read-permission saknas: justera den befintliga tokenen; lägg inte till Edit/Write."
if ! confirm "Matchar R1/R2/R3 read-behoven utan write-scope?"; then
  warn "Stanna tills read-scope är korrekt."
  exit 2
fi

stage "Cloudflare Secrets Store · befintliga värden"
say "Verifiera att runtime återanvänder centrala credentials i stället för duplicerade kopior."
open_url "https://dash.cloudflare.com/"
step "Gå till Workers & Pages → Secrets Store för samma Cloudflare-account som Skvallerbyttan."
step "Verifiera CLOUDFLARE_API_TOKEN_R1, CLOUDFLARE_API_TOKEN_R2 och CLOUDFLARE_API_TOKEN_R3."
step "Verifiera KROSA_MAJA_CLIENT_SECRET; wrangler.jsonc binder den som GITHUB_OAUTH_CLIENT_SECRET."
step "Kontrollera att varje bunden Secrets Store-secret får användas av Workers."
if ! confirm "Finns bindings/secrets och är Workers-scope korrekt?"; then
  warn "Ändra endast befintlig binding/scope; exportera inte secretvärden."
  exit 2
fi

stage "Worker runtime · secretnamn"
say "Verifiera runtime-secrets i Cloudflare utan att kopiera ut deras värden."
open_url "https://dash.cloudflare.com/"
step "Öppna Workers & Pages → skvallerbyttan → Settings och kontrollera runtime variables/secrets."
step "Krävs: GAMNACKEN_GITHUB_APP_CLIENT_ID, GAMNACKEN_GITHUB_APP_PRIVATE_KEY, SKVALLERBYTTAN_SESSION_SECRET och SKVALLERBYTTAN_WEBHOOK_SECRET."
step "Vid aktiverade integrationer: CLOUDFLARE_NOTIFICATIONS_WEBHOOK_SECRET och CLOUDFLARE_CASB_WEBHOOK_SECRET."
step "SKVALLERBYTTAN_READ_API_TOKEN behövs endast om machine read API ska användas."
note "GitHub Actions ska inte synka dessa värden och ska inte bära Cloudflare deploycredential."
if ! confirm "Är de runtime-secrets som faktiskt används konfigurerade?"; then
  warn "Provisionering/rotation görs manuellt på provider-sidan; lägg aldrig värden i Git/repo/chatt."
  exit 2
fi

stage "Webhookkopplingar"
say "Kontrollera endast att provider- och runtime-sidan använder samma befintliga hemlighet."
open_url "https://github.com/settings/apps"
step "För aktiv GitHub provider-webhook: verifiera kopplingen till SKVALLERBYTTAN_WEBHOOK_SECRET."
open_url "https://dash.cloudflare.com/"
step "För Notifications/Workers Issues: verifiera kopplingen till CLOUDFLARE_NOTIFICATIONS_WEBHOOK_SECRET."
step "För CASB: verifiera kopplingen till CLOUDFLARE_CASB_WEBHOOK_SECRET om CASB-ingress används."
step "Visa, logga eller klistra inte in secretvärden i wizarden. Rotation görs endast vid faktisk mismatch och samordnat på båda sidor."
if ! confirm "Är alla aktiva webhookkopplingar synkroniserade?"; then
  warn "Lämna berörd ingress avstängd/oklar tills provider och runtime är synkroniserade."
  exit 2
fi

stage "Cloudflare Workers Builds · deployidentitet"
say "Verifiera att deploy sker via Cloudflare Workers Builds, inte via GitHub-hostad Cloudflare-token."
open_url "https://dash.cloudflare.com/"
step "Öppna Workers & Pages → skvallerbyttan → Builds/Settings."
step "Verifiera repository Avkroken/Avkroken, branch main och root directory apps/skvallerbyttan."
step "Verifiera production command: npm run deploy:workers-builds."
step "GitHub Actions ska endast köra repository-CI; lägg inte till Cloudflare deploycredential där."
if ! confirm "Matchar Workers Builds repositoryts deploykontrakt?"; then
  warn "Ändra inte deployment i denna wizard; dokumentera avvikelsen och hantera den separat."
  exit 2
fi

stage "Skvallerbyttan · capability verification"
say "Slutkontrollen görs från Skvallerbyttans privata dashboard."
open_url "https://skvallerbyttan.denied.se/"
step "Logga in och öppna Insyn. Kör Uppdatera för en explicit read-only reconciliation."
step "Verifiera GitHub App-proben samt Cloudflare R1, R2 och R3. Desired reads ska inte visa permission_denied."
step "Organization-only GitHub capabilities får visa not_supported när owner fortfarande är en GitHub User."
step "Kontrollera freshness/last success och att inga credentialvärden exponeras i dashboard/API."
if ! confirm "Är önskade read-only capabilities tillgängliga eller korrekt markerade?"; then
  warn "Använd capability-status för att hitta den specifika saknade read-permissionen; bredda inte tokenklasser generellt."
  exit 2
fi

finish
