blank_issues_enabled: false
contact_links:
  - name: Frågor, idéer och diskussion
    url: https://github.com/blixten85/.github/discussions
    about: Ställ frågor och diskutera idéer eller annat som inte är ett reproducerbart fel eller ett konkret förbättringsförslag.
